import Head from 'next/head'
import Image from 'next/image'
import { toast } from 'react-toastify'
import About from '../components/parts/About'
import Hero from '../components/parts/Hero'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Cloud E-Bus Seat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
    
  
    </div>
  )
}
